Only show the basename of the command in messages.

diff --git a/zfs-snapshot-clean b/zfs-snapshot-clean
--- a/zfs-snapshot-clean
+++ b/zfs-snapshot-clean
@@ -51,6 +51,7 @@ esac
 type zfs >/dev/null 2>&1 || PATH="$PATH:/sbin"
 
 VERSION=0.1.3
+MYNAME="${0##*/}"
 DRYRUN=
 VERBOSE=
 DEFAULT_DAYSPEC=7D6W6M2Y
@@ -71,7 +72,7 @@ EOF
 usage () {
     version
     cat <<EOF
-Usage: $0 [OPTION ...] {VOLUME|MOUNTPOINT} ...
+Usage: $MYNAME [OPTION ...] {VOLUME|MOUNTPOINT} ...
   -k DAYSPEC      Specify how snapshots are kept (Default: "$DEFAULT_DAYSPEC")
   -p PREFIX       Specify the prefix before the date part (Default: none)
   -r              Delete recursively
@@ -130,7 +131,7 @@ main () {
     shift "$((OPTIND - 1))"
 
     if [ $# -eq 0 ]; then
-        echo "$0: no ZFS volume/mountpoint is given"
+        echo "$MYNAME: no ZFS volume/mountpoint is given"
         usage
     fi
 
@@ -152,7 +153,7 @@ parse_dayspec () {
     while [ -n "$str" ]; do
         number="$(expr "$str" : "^\([0-9]*\).*")"
         if [ -z "$str" ]; then
-            echo "$0: specification format error: $spec" >&2
+            echo "$MYNAME: specification format error: $spec" >&2
             usage
         fi
 
@@ -176,13 +177,13 @@ parse_dayspec () {
                 str="${str#Y}"
                 ;;
             *)
-                echo "$0: specification format error: $spec" >&2
+                echo "$MYNAME: specification format error: $spec" >&2
                 usage
                 ;;
         esac
     done
 
-    info "$0 only keeps snapshots of the most recent:"
+    info "$MYNAME only keeps snapshots of the most recent:"
     [ $NDAYS   -gt 0 ] && info "- $NDAYS days"
     [ $NWEEKS  -gt 0 ] && info "- $NWEEKS Sundays"
     [ $NMONTHS -gt 0 ] && info "- $NMONTHS months' first days"
