Add support for non-mounted ZFS and fix for Solaris.

diff --git a/zfs-snapshot-clean b/zfs-snapshot-clean
--- a/zfs-snapshot-clean
+++ b/zfs-snapshot-clean
@@ -29,26 +29,29 @@
 # OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 # SUCH DAMAGE.
 
-case "$(uname -s)" in
+case "`uname -s`" in
     SunOS)
         type local >/dev/null 2>&1 || exec /usr/xpg4/bin/sh "$0" "$@"
         awk () {
             /usr/xpg4/bin/awk "$@"
         }
-        for cmd in /usr/gnu/bin/date /usr/sfw/bin/gdate; do
+        for cmd in /usr/gnu/bin/date /usr/sfw/bin/gdate /usr/local/bin/gdate; do
             if [ -x "$cmd" ]; then
                 DATE_CMD="$cmd"
                 break
             fi
         done
-        : ${DATE_CMD:=date}
+        : ${DATE_CMD:=gdate}
         date () {
             "$DATE_CMD" "$@"
         }
         ;;
 esac
 
-VERSION=0.1.3
+export PATH
+PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/sbin:/usr/sbin
+
+VERSION=0.1.4
 DRYRUN=
 VERBOSE=
 DEFAULT_DAYSPEC=7D6W6M2Y
@@ -69,7 +72,7 @@ EOF
 usage () {
     version
     cat <<EOF
-Usage: $0 [OPTION ...] {VOLUME|MOUNTPOINT} ...
+Usage: ${0##*/} [OPTION ...] {VOLUME|MOUNTPOINT} ...
   -k DAYSPEC      Specify how snapshots are kept (Default: "$DEFAULT_DAYSPEC")
   -p PREFIX       Specify the prefix before the date part (Default: none)
   -r              Delete recursively
@@ -128,7 +131,7 @@ main () {
     shift "$((OPTIND - 1))"
 
     if [ $# -eq 0 ]; then
-        echo "$0: no ZFS volume/mountpoint is given"
+        echo "${0##*/}: no ZFS volume/mountpoint is given"
         usage
     fi
 
@@ -150,7 +153,7 @@ parse_dayspec () {
     while [ -n "$str" ]; do
         number="$(expr "$str" : "^\([0-9]*\).*")"
         if [ -z "$str" ]; then
-            echo "$0: specification format error: $spec" >&2
+            echo "${0##*/}: specification format error: $spec" >&2
             usage
         fi
 
@@ -174,13 +177,13 @@ parse_dayspec () {
                 str="${str#Y}"
                 ;;
             *)
-                echo "$0: specification format error: $spec" >&2
+                echo "${0##*/}: specification format error: $spec" >&2
                 usage
                 ;;
         esac
     done
 
-    info "$0 only keeps snapshots of the most recent:"
+    info "${0##*/} only keeps snapshots of the most recent:"
     [ $NDAYS   -gt 0 ] && info "- $NDAYS days"
     [ $NWEEKS  -gt 0 ] && info "- $NWEEKS Sundays"
     [ $NMONTHS -gt 0 ] && info "- $NMONTHS months' first days"
@@ -200,43 +203,18 @@ run () {
     fi
 }
 
-zfs_find_fs () {
-    local volume="$1"; shift
-    local volumename= used avail refer mountpoint=
-
-    zfs list | while read volumename used avail refer mountpoint; do
-        case "$mountpoint" in
-            -)
-                continue
-                ;;
-            legacy)
-                mountpoint="$(mount -v | while read dev on mountpoint options; do
-                    if [ "$dev" = "$volumename" ] &&
-                        expr "$options" : '.*[( ]zfs[, )].*' > /dev/null; then
-                        echo "$mountpoint"
-                        exit
-                    fi
-                done)"
-                [ -n "$mountpoint" ] || continue
-                ;;
-        esac
-        if [ "$volume" = "$volumename" -o "$volume" = "$mountpoint" ]; then
-            echo "$volumename $mountpoint"
-            break
-        fi
-    done
+get_snapshots () {
+     zfs list -d 1 -t snapshot -H -o name $1 | sed -e 's/.*@//'
 }
 
 zfs_snapshot_clean () {
-    local volume="$1"; shift
-    local volumename= mountpoint=
+    local volumename="$1"; shift
     local name date number
 
-    set -- $(zfs_find_fs "$volume"); volumename="$1"; mountpoint="$2"
-
-    if [ -z "$volumename" -o -z "$mountpoint" ]; then
-        echo "$volume: not a ZFS volume" >&2
-        return 1
+    if ! zfs list -o name $volumename >/dev/null 2>&1
+    then
+	echo "$volumename: not a ZFS volume" >&2
+	return 1
     fi
 
     info "cleaning $volumename"
@@ -245,7 +223,7 @@ zfs_snapshot_clean () {
         # bit 1
         { days; weeks; months; years; } | sort -u
         # bit 2
-        ls -1 "$mountpoint/$PREFIX"/.zfs/snapshot | while read name; do
+        get_snapshots $volumename | while read name; do
             case "$name" in
                 "$PREFIX"[1-9][0-9][0-9][0-9]-[01][0-9]-[0-3][0-9]) ;;
                 *) continue ;;
